spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#自动创建、更新、验证数据库表结构
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
  #文件上传大小限制
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  activiti:
      databaseSchemaUpdate: true #activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
      dbIdentityUsed: false #检查身份信息表是否存在
      activityFontName: "宋体" #设置字体
      labelFontName: "宋体"  #设置字体
      annotationFontName: "宋体"
      check-process-definitions: false #自动部署验证
#      db-identity-used: true org/activiti/db/create/activiti.mysql.create.history.sql activeti sql文件存放
#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.activiti.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
server:
  port: 8083